spring:
  application:
    name: razorpay

  # PostgresSQL Database Connection Settings
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/razorpayDB}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:admin}
    driver-class-name: org.postgresql.Driver
  data.redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    ttl-duration: 5

  # JPA / Hibernate Configurations
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        #format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Kafka Configurations
  kafka:
    listener:
      ack-mode: manual
    bootstrap-servers: ${KAFKA_BROKERS:localhost:29092}
    producer:
      # 'all' means the leader broker waits for all in-sync replicas (ISRs) to acknowledge the write.
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
        # The maximum number of unacknowledged requests the client will send on a single connection before blocking.
        max.in.flight.requests.per.connection: 5
        retries: 3
        spring.json.add.type.headers: false
    consumer:
      group-id: razorpay-monolith
      auto-offset-reset: earliest
      # Paired with 'ack-mode: manual', this ensures you only commit offsets after processing succeeds.
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.razorpay.*"
        spring.json.use.type.headers: false
        # Because type headers are ignored, this forces the consumer to parse the JSON value into a generic LinkedHashMap instead of mapping it to a specific strict Java class.
        spring.json.value.default.type: java.util.LinkedHashMap

vault:
  master-key: X7vG9mQK2zYWpB4s5uRtE1dF3nG6hJ8kLmNpQrStUvW=
  randomToken-length: 32

payment:
  simulator:
    poll-interval-ms: 5000
    chaos-mode: SUCCESS
    methods:
      CARD:
        min-delay-seconds: 2
        max-delay-seconds: 6
        success-rate: 90
      UPI:
        min-delay-seconds: 1
        max-delay-seconds: 3
        success-rate: 95
      NET_BANKING:
        min-delay-seconds: 4
        max-delay-seconds: 10
        success-rate: 80

api-key:
  keyId-length: 24
  rawSecret-length: 40
  gracePeriod-expiry-time-in-hour: 24

jwt:
  secret-key: 7yH8zX$mK#q2wB!vE9xZ6*fN3sU1pA5jD8cK0mQ!rT4vW9zB2xY5


app:
  rate-limit:
    method: fixed
    use-case:
      api-key:
        requests-per-minute: 30